---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Install OS package {{ virtualenv_os_package }}"
  package:
    name: "{{ virtualenv_os_package }}"

- name: "Install extractor into {{ extractor_venv }}"
  pip:
    # no release on pypi yet
    chdir: ..
    name: .
    state: latest
    virtualenv: "{{ extractor_venv }}"
    virtualenv_python: python3

- name: "Create configuration directory {{ extractor_config_dir }}"
  file:
    dest: "{{ extractor_config_dir }}"
    state: directory

- name: "Create group {{ extractor_group }}"
  group:
    name: "{{ extractor_group }}"
    state: present

- name: "Create user {{ extractor_user }}"
  user:
    name: "{{ extractor_user }}"
    group: "{{ extractor_group }}"
    home: "{{ extractor_user_home }}"

- name: "Create config file {{ extractor_config_file }}"
  template:
    src: extractor.ini.j2
    dest: "{{ extractor_config_file }}"
    owner: root
    group: "{{ extractor_group }}"
    mode: 0640

- name: Manage service
  include_tasks: manage-service.yml
  when: ansible_service_mgr == "systemd" and not extractor_instances

- name: Manage service instances
  include_tasks: manage-service-instances.yml
  when: ansible_service_mgr == "systemd" and extractor_instances
