---
- name: "Create the {{ extractor_service }} systemd service unit"
  template:
    src: service.systemd.j2
    dest: "/etc/systemd/system/{{ extractor_service }}.service"
    owner: root
    group: root

- name: "Enable and start {{ extractor_service }}"
  systemd:
    name: "{{ extractor_service }}"
    state: started
    enabled: true
    daemon_reload: yes
