---
- name: "Create the {{ extractor_service }} systemd service unit"
  template:
    src: service.systemd.j2
    dest: "/etc/systemd/system/{{ extractor_service }}@.service"
    owner: root
    group: root

- name: "Enable and start {{ extractor_service }} instances"
  systemd:
    name: "{{ extractor_service }}@{{ item }}"
    state: started
    enabled: true
    daemon_reload: yes
  loop: "{{ range(1, extractor_instances + 1, 1) | list }}"
