---
- name: "Create the {{ expander_service }} systemd service unit"
  template:
    src: service.systemd.j2
    dest: "/etc/systemd/system/{{ expander_service }}.service"
    owner: root
    group: root

- name: "Enable and start {{ expander_service }}"
  systemd:
    name: "{{ expander_service }}"
    state: started
    enabled: true
    daemon_reload: yes
