---
extractor_service: extractor-deduper

extractor_user: "{{ extractor_service }}"
extractor_group: "{{ extractor_service }}"
extractor_user_home: "/var/lib/{{ extractor_user }}"

extractor_venv: "/opt/{{ extractor_service }}"
extractor_config_dir: "{{ extractor_venv }}/etc"
extractor_config_file: "{{ extractor_config_dir }}/extractor.ini"
extractor_service_command: "{{ extractor_venv }}/bin/{{ extractor_service
  }} --config-file {{ extractor_config_file }}"

extractor_instances: 3

karton_log_level: INFO

minio_access_key: karton
minio_secret_key: secret
minio_address: localhost:9000
minio_bucket: karton
minio_secure: 0

redis_host: localhost
redis_port: 6379

extractor_use_deduper: True
extractor_use_cache: True
extractor_reports_key: extractor.reports
extractor_job_cache_key: "extractor.cache:"
extractor_correlator_reports_identity: extractor.correlator-for-job-

extractor_peekaboo_url: "http://127.0.0.1:8100"
extractor_peekaboo_backoff: 0.5
extractor_peekaboo_retries: 5

extractor_peekaboo_tracker_job_age_cutoff: 600

extractor_cache_responder_age_out_interval: 60
extractor_cache_responder_max_age: 240

extractor_deduper_running_key: extractor.running
extractor_deduper_recheck_interval: 2
extractor_deduper_cutoff: 60
extractor_deduper_gc_interval: "{{ extractor_deduper_cutoff * 2 }}"

extractor_poker_jobs_key: extractor.jobs
extractor_poker_recheck_cutoff: 60
extractor_poker_poking_delay: 3
extractor_poker_timeout: 1

extractor_api_host: "127.0.0.1"
extractor_api_port: 8200
