---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Install OS package {{ virtualenv_os_package }}"
  package:
    name:
    - "{{ virtualenv_os_package }}"

- name: "Install OS dependencies"
  package:
    name: "{{ karton_os_dependencies[karton_service] }}"
  when: karton_service in karton_os_dependencies

- name: "Install {{ karton_package }} into {{ karton_venv }}"
  pip:
    name:
    - "{{ karton_package }}"
    state: latest
    virtualenv: "{{ karton_venv }}"
    virtualenv_python: python3

- name: "Create configuration directory {{ karton_config_dir }}"
  file:
    dest: "{{ karton_config_dir }}"
    state: directory

- name: "Create group {{ karton_group }}"
  group:
    name: "{{ karton_group }}"
    state: present

- name: "Create user {{ karton_user }}"
  user:
    name: "{{ karton_user }}"
    group: "{{ karton_group }}"
    home: "{{ karton_user_home }}"

- name: "Create config file {{ karton_config_file }}"
  template:
    src: karton.ini.j2
    dest: "{{ karton_config_file }}"
    owner: root
    group: "{{ karton_group }}"
    mode: 0640

- name: "Create the {{ karton_service }} systemd service unit"
  template:
    src: service.systemd.j2
    dest: "/etc/systemd/system/{{ karton_service }}@.service"
    owner: root
    group: root
  when: ansible_service_mgr == "systemd"

- name: "Enable and start {{ karton_service }} instances"
  systemd:
    name: "{{ karton_service }}@{{ item }}"
    state: started
    enabled: true
    daemon_reload: yes
  loop: "{{ range(1, karton_instances + 1, 1) | list }}"
  when: ansible_service_mgr == "systemd"
