- name: "Install minio"
  hosts: minio
  tags: minio
  become: true
  roles:
    - role: atosatto.minio
  vars:
    minio_server_datadirs:
      - "/var/lib/minio"
    minio_access_key: "karton"

- name: "Install redis"
  hosts: redis
  tags: redis
  become: true
  roles:
    - role: geerlingguy.redis

- name: "Install Karton System"
  hosts: karton_system
  tags: karton-system
  become: true
  roles:
    - role: karton-service
  vars:
    karton_service: "karton-system"
    karton_package: "karton-core"
    karton_extra_args: "--setup-bucket"

- name: "Install Karton Logger"
  hosts: karton_logger
  tags: karton-logger
  become: true
  roles:
    - role: karton-service
  vars:
    karton_service: "karton-logs"
    karton_package: "karton-core"
    karton_command: "karton"
    karton_extra_args: "logs"
    karton_instances: 1

- name: "Install Karton Classifier"
  hosts: karton_classifier
  tags: karton-classifier
  become: true
  roles:
    - role: karton-service

- name: "Install Karton Archive Extractor"
  hosts: karton_archive_extractor
  tags: karton-archive-extractor
  become: true
  roles:
    - role: karton-service
  vars:
    karton_service: "karton-archive-extractor"

- name: "Install Karton Dashboard"
  hosts: karton_dashboard
  tags: karton-dashboard
  become: true
  roles:
    - role: karton-dashboard

- name: "Install Extractor Deduper"
  hosts: extractor_deduper
  tags: extractor-deduper
  become: true
  roles:
    - role: extractor-service

- name: "Install Extractor Cache Responder"
  hosts: extractor_cache_responder
  tags: extractor-cache-responder
  become: true
  roles:
    - role: extractor-service
  vars:
    extractor_service: extractor-cache-responder

- name: "Install Extractor Peekaboo Submitter"
  hosts: extractor_peekaboo_submitter
  tags: extractor-peekaboo-submitter
  become: true
  roles:
    - role: extractor-service
  vars:
    extractor_service: extractor-peekaboo-submitter

- name: "Install Extractor Poker"
  hosts: extractor_poker
  tags: extractor-poker
  become: true
  roles:
    - role: extractor-service
  vars:
    extractor_service: extractor-poker

- name: "Install Extractor Peekaboo Tracker"
  hosts: extractor_peekaboo_tracker
  tags: extractor-peekaboo-tracker
  become: true
  roles:
    - role: extractor-service
  vars:
    extractor_service: extractor-peekaboo-tracker

- name: "Install Extractor Correlator"
  hosts: extractor_correlator
  tags: extractor-correlator
  become: true
  roles:
    - role: extractor-service
  vars:
    extractor_service: extractor-correlator

- name: "Install Extractor API"
  hosts: extractor_api
  tags: extractor-api
  become: true
  roles:
    - role: extractor-service
  vars:
    extractor_service: extractor-api
    extractor_instances: 0

- name: Clean up installer directory
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Remove temporary storage files of deployed passwords
      file:
        state: absent
        path: "{{ item }}"
      with_items:
        - minio_secret_key
