---
expander_service: expander-deduper

expander_user: "{{ expander_service }}"
expander_group: "{{ expander_service }}"
expander_user_home: "/var/lib/{{ expander_user }}"

expander_venv: "/opt/{{ expander_service }}"
expander_config_dir: "{{ expander_venv }}/etc"
expander_config_file: "{{ expander_config_dir }}/expander.ini"
expander_service_command: "{{ expander_venv }}/bin/{{ expander_service
  }} --config-file {{ expander_config_file }}"

expander_instances: 3

karton_log_level: INFO

s3_access_key: karton
s3_secret_key: secret
s3_address: http://localhost:9000
s3_bucket: karton

redis_host: localhost
redis_port: 6379

expander_use_deduper: True
expander_use_cache: True
expander_reports_key: expander.reports
expander_job_cache_key: "expander.cache:"
expander_correlator_reports_identity: expander.correlator-for-job-

expander_peekaboo_url: "http://127.0.0.1:8100"
expander_peekaboo_backoff: 0.5
expander_peekaboo_retries: 5

expander_peekaboo_tracker_job_age_cutoff: 600

expander_cache_responder_age_out_interval: 60
expander_cache_responder_max_age: 240

expander_deduper_running_key: expander.running
expander_deduper_recheck_interval: 2
expander_deduper_cutoff: 60
expander_deduper_gc_interval: "{{ expander_deduper_cutoff * 2 }}"

expander_poker_jobs_key: expander.jobs
expander_poker_recheck_cutoff: 60
expander_poker_poking_delay: 3
expander_poker_timeout: 1

expander_api_host: "127.0.0.1"
expander_api_port: 8200
